export {default as Home} from './pages/home/Home'
export {default as Register} from './pages/register/Register'
export {default as Login} from './pages/login/Login'
export {default as NotFound} from './pages/NotFound/NotFound'
export {default as Sidebar} from './components/Sidebar/Sidebar'
export {default as Header} from './components/Header/Header'